<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Check if file is uploaded
    if ($_FILES['productImage']['size'] > 0) {
        // Endpoint URL for uploading image
        $uploadImageUrl = "https://localhost:7262/api/Product/upload";

        // Initialize cURL session for image upload
        $ch_upload = curl_init();
        curl_setopt($ch_upload, CURLOPT_URL, $uploadImageUrl);
        curl_setopt($ch_upload, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch_upload, CURLOPT_POST, true);
        curl_setopt($ch_upload, CURLOPT_SSL_VERIFYHOST, false); // Disable SSL verification for testing
        curl_setopt($ch_upload, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch_upload, CURLOPT_POSTFIELDS, [
            'file' => new CURLFile($_FILES['productImage']['tmp_name'], $_FILES['productImage']['type'], $_FILES['productImage']['name'])
        ]);

        // Execute cURL session for image upload
        $response_upload = curl_exec($ch_upload);

        // Check for cURL errors for image upload
        if (curl_errno($ch_upload)) {
            echo 'Error:' . curl_error($ch_upload);
            exit();
        }

        // Close cURL session for image upload
        curl_close($ch_upload);

        // Decode JSON response
        $uploadResponse = json_decode($response_upload, true);

        // Check if image upload was successful
        if ($uploadResponse) {
            $imageUrl = 'images/' . $_FILES['productImage']['name'];

            // Proceed to create product with the uploaded image URL
            createProduct($imageUrl);
        } 
        else {
            // Handle error case for image upload
            echo "Failed to upload image. Please try again.";
            exit();
        }
    } else {
        // Handle case where no file is uploaded
        echo "No image file uploaded.";
        exit();
    }
}

function createProduct($imageUrl) {
    // Retrieve other form data
    $productName = $_POST['productName'] ?? '';
    $description = $_POST['description'] ?? '';
    $price = floatval($_POST['price'] ?? 0);

    // Prepare product data including the uploaded image URL
    $productData = [
        'productID' => 0, // Assuming the ID is auto-generated by the backend
        'productName' => $productName,
        'description' => $description,
        'price' => $price,
        'isLocked' => false, // Assuming default value
        'imageUrl' => $imageUrl
    ];

    // Endpoint URL for creating product
    $productApiUrl = "https://localhost:7262/api/Product";

    // Initialize cURL session for product creation
    $ch_product = curl_init();
    curl_setopt($ch_product, CURLOPT_URL, $productApiUrl);
    curl_setopt($ch_product, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch_product, CURLOPT_POST, true);
    curl_setopt($ch_product, CURLOPT_HTTPHEADER, ['Content-Type: application/json']); // Set JSON headers
    curl_setopt($ch_product, CURLOPT_POSTFIELDS, json_encode($productData)); // Send data as JSON
    curl_setopt($ch_product, CURLOPT_SSL_VERIFYHOST, false); // Disable SSL verification for testing
    curl_setopt($ch_product, CURLOPT_SSL_VERIFYPEER, false); // Disable SSL verification for testing

    // Execute cURL session for product creation
    $response_product = curl_exec($ch_product);

    // Check for cURL errors for product creation
    if (curl_errno($ch_product)) {
        echo 'Error:' . curl_error($ch_product);
        exit();
    }

    // Close cURL session for product creation
    curl_close($ch_product);

    // Decode JSON response
    $productResponse = json_decode($response_product, true);

    // Check if product creation was successful
   
        // Redirect or show success message
        header("Location: ../viewProduct.php");
        exit();
  
}
?>
